### ISSUE TITLE
Dark mode browser preference messes up the readability (white text on white background)

### ISSUE THREAD

**Issue by tristanhollman** [dannyBies/RandomHoliday#1]
Hey there,

Just wanted to let you know, that currently the colors are a bit messed up when viewed in a browser that prefers dark mode.
The text color of the is set to `white` on the `body` [here](https://github.com/dannyBies/RandomHoliday/blob/3d3115f2652bc7bd7695dd860a95d9fd6f0391e5/src/app/globals.css#L20C37-L20C37). But because the background color of the input fields isn't changed to a darker color you end up with white text on a white background, which makes it a bit hard to read :)
![image](https://github.com/dannyBies/RandomHoliday/assets/8666039/4cf956a4-9464-46eb-a791-261efcc23ac3)

Apart from this the app is looking very sharp, nice work!

Kind regards,
Tristan

**Comment by dannyBies** [comment]
Hey Tristan!
Thanks for reporting this. I'm currently not planning to add full support for dark mode but it should definitely be at least useable, I've fixed the issue in https://github.com/dannyBies/RandomHoliday/commit/8443d4ec7b0a7424e2b179d82bb525ffecac9116.

Feel free to let me know if you find any other issues 👍
